version: '3.8'

services:
  qwen-api:
    build: .
    container_name: qwen-cli-api-server
    ports:
      - "3008:3008"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3008/api/health"]
      interval: 600s
      timeout: 10s
      retries: 3
      start_period: 40s
